services:
  web:
    image: ghcr.io/alvine998/naturafoods2:latest
    build: .
    ports:
      - "3016:3016"
    env_file:
      - .env
    environment:
      - PORT=3016
    restart: unless-stopped
